TM-14 - servico checar token
Maua-Dev/mss_autenticacao pull request #12
Opened 2021-08-20 13:20 UTC by goodguyplayer

Adicionado método verificar login.

Seria bom, porém, discutir como controlar os possíveis erros que o sistema pode gerar. Tipo "Token inválido", "Acabou o tempo de vida do seu token", "A assinatura não combina"

2021-08-22 22:54 UTC, VitorMartin requested changes

2021-08-22 22:54 UTC, VitorMartin commented on src/controladores/c_verificar_token.py
> +class CVerificarToken():
- [ ] Colocar os controladores de FastAPI numa pasta: `src/controladores/fastapi`
- [ ] Mudar nome do arquivo e classe para "c_verificar_token **_fastapi**"

2021-08-22 22:54 UTC, VitorMartin commented on .gitignore
> -.vscode/
Consertou a arvore Git ou só adicionou as pastas no `.gitignore`?

2021-08-22 22:54 UTC, VitorMartin commented on src/main.py
> +controllerVerificarToken = CVerificarToken(AuthJWT())
Criar a factory de controlador. Seguir exemplo do [MSS Ger Usr](https://github.com/Maua-Dev/mss_gerenciamento_usuarios/tree/TM-25-refactor-main-ctrl/src/controladores)

2021-08-22 22:54 UTC, VitorMartin commented on src/repositorios/erros/erros_jwt.py
> +class ErroDecoderFalha(Exception):
Renomear: ErroFalhaDecoder

2021-08-22 22:54 UTC, VitorMartin commented on tests/controladores/test_c_verificar_token.py
> +    assert True
Ta testando de vdd?

2021-08-24 13:01 UTC, goodguyplayer commented on .gitignore
> -.vscode/
Não entendi a pergunta

2021-08-24 13:02 UTC, goodguyplayer commented on tests/controladores/test_c_verificar_token.py
> +    assert True
Para esse teste, não. Achei que talvez fosse melhor manter sem um token por enquanto e adicionar depois quando tivermos uma chave definitiva.

2021-08-24 19:02 UTC, VitorMartin requested changes

2021-08-24 19:02 UTC, VitorMartin commented on src/main.py
> +fabricaFastAPI = FabricaControladorFastAPI(AuthJWT())
Aqui vc instancia o controlador em si, não a fabrica. Só muda o nome da variavel pra `controlador`

2021-08-24 22:00 UTC, VitorMartin approved these changes
Mto bom!

2021-08-24 23:07 UTC, merged