TM-15  Servico de recuperacao de senha
Maua-Dev/mss_autenticacao pull request #21
Opened 2021-10-09 13:14 UTC by goodguyplayer

Adicionado serviço de recuperação de senha.

2021-10-10 23:54 UTC, VitorMartin requested changes
Trocar o status do `http` pelo `FastAPI` (`from fastapi import status`)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses

2021-10-10 23:54 UTC, VitorMartin commented on src/controladores/fastapi/c_alterar_senha.py
> +                return Response(content="Senha atualizada com successo", status_code=HTTPStatus.ACCEPTED)
Alterar status para 204 - No Content

2021-10-10 23:54 UTC, VitorMartin commented on src/controladores/fastapi/c_alterar_senha.py
> +                return Response(content="Email não bate", status_code=HTTPStatus.BAD_REQUEST)
Alterar status para 401 - Unauthorized

2021-10-10 23:54 UTC, VitorMartin commented on src/controladores/fastapi/c_alterar_senha.py
> +            return Response(content="Erro - Email não encontrado", status_code=HTTPStatus.INTERNAL_SERVER_ERROR)
Alterar status para 404 - Not Found

2021-10-10 23:54 UTC, VitorMartin commented on src/controladores/fastapi/c_esqueci_senha.py
> +            response = Response(content="Esse email não existe", status_code=400)
Alterar status para 404 - Not Found

2021-10-10 23:54 UTC, VitorMartin commented on src/controladores/fastapi/c_esqueci_senha.py
> +            response = Response(content="error undefined", status_code=400)
Alterar status para 500 - Internal Server Error

2021-10-10 23:54 UTC, VitorMartin commented on src/main.py
> +async def esqueciSenha(request: Request):
Validar o corpo do request com Pydantic, tipo {"token": Token, "email": str, "senha": str}

Validar resposta tambem

2021-10-10 23:54 UTC, VitorMartin commented on src/main.py
> +async def esqueciSenha(request: Request):
Validar request com Pydantic

Validar resposta tambem

2021-10-11 11:14 UTC, goodguyplayer commented
Estou tendo problemas em alterar o status de resposta para "204 - No Content". Devido a documentações, a resposta 204 não retorna body.

2021-10-11 19:44 UTC, VitorMartin commented on src/controladores/fastapi/c_esqueci_senha.py
> +            response = Response(content=content, status_code=status.HTTP_201_CREATED)
202

2021-10-11 19:44 UTC, VitorMartin commented on src/controladores/fastapi/c_alterar_senha.py
> +                return Response(content="Email não bate", status_code=status.HTTP_400_BAD_REQUEST)
404

2021-10-11 19:46 UTC, VitorMartin commented on src/controladores/fastapi/c_alterar_senha.py
> +            token = self.auth.verificarToken(alterarSenha.token)
levantar `ErroAuth` e status 403

2021-10-11 19:47 UTC, VitorMartin commented on src/controladores/fastapi/c_alterar_senha.py
> +            return Response(content="Erro inesperado", status_code=status.HTTP_404_NOT_FOUND)
500

2021-10-11 19:48 UTC, VitorMartin commented on src/controladores/fastapi/http/requisicoes.py
> +class EsqueciSenha(BaseModel):
`ModeloEsqueciSenha`

2021-10-11 19:49 UTC, VitorMartin commented on src/main.py
> +@app.post("/esquecisenha")
`@app.post("/esquecisenha", response_model=...)`

2021-10-21 22:48 UTC, VitorMartin requested changes
Status 202 nao retorna corpo. Entao troca pra 200.

O resto ficou animal!

2021-11-02 18:54 UTC, VitorMartin approved these changes

2021-11-02 22:54 UTC, merged