Issue2 geracao token
Maua-Dev/mss_autenticacao pull request #7
Opened 2021-08-11 01:11 UTC by goodguyplayer

Serviço de geração de token.
- Para gerar o token, post request para /token. 
- Usado um arquivo .env para esconder a senha. Não permanente, podemos mudar mais tarde caso achem necessário.
- Tentei usar a [Padronização definida](https://github.com/orgs/Maua-Dev/teams/squad-marocas/discussions/1).

2021-08-11 01:16 UTC, goodguyplayer commented
Havia dado erro no teste que era pra dar erro. Corrigido o erro de verificação do erro.

2021-08-11 01:23 UTC, VitorMartin commented on src/models/m_jwt_chave.py
> +class JWTChave(BaseModel):
Trocar o nome do arquivo para `jwt_chave.py`

Model não precisa especificar o tipo

2021-08-11 01:23 UTC, VitorMartin commented on src/models/m_jwt_chave.py
> +    privateChave : str
chavePrivada

2021-08-11 01:24 UTC, VitorMartin commented on src/models/m_jwt_chave.py
> +    def senhaNotEmpty(cls, v):
senhaNaoVazia

2021-08-11 01:26 UTC, VitorMartin commented on src/models/m_jwt_token.py
> +class JWTToken(BaseModel):
Trocar o nome do arquivo para `token.py`

Model não precisa especificar o tipo

2021-08-11 01:54 UTC, VitorMartin requested changes
Remover o `JWT` dos nomes, pois isso se trata de uma forma de implementação. Onde vai ter nome de JWT é no repositório, onde você irá realmente utilizar a biblioteca JWT

2021-08-11 01:54 UTC, VitorMartin commented on src/models/m_jwt_token.py
> +    def payloadNotEmpty(cls, v):
Traduzir os validadores para português (ex: `...NaoVazio`)

2021-08-11 01:54 UTC, VitorMartin commented on src/models/m_jwt_token.py
> +            raise ValueError("Payload Vazio")
Para cada erro, criar uma classe específica. Seguir exemplo do MSS Ger Usr.

Por mais simples que seja cada erro, isso serve pra nó termos o total controle das excecoes do nosso sistema.

2021-08-11 01:54 UTC, VitorMartin commented on src/models/m_jwt_token.py
> +    def criarJWTTokenPorDictionary(d: dict):
Sugestão: alterar nome para `fromDict(d)`

Assim, o código fica bem legível, por exemplo: `Token.fromDict(d)` ou `Usuario.fromDict(d)`

2021-08-11 01:54 UTC, VitorMartin commented on src/usecases/uc_criar_chave.py
> +    def criarChave(self):
Dá uma olhada no método `__call__()`.

Com ele vc pode chamar a própria instância da classe como uma função

Por exemplo:

`chave = UCCriarChave (encriptografia) ( )`

o primeiro parêntesis instancia a classe e o segundo chama o método `.__call__()`  por padrão

2021-08-11 01:54 UTC, VitorMartin commented on .vscode/settings.json
> +{
Adiciona os arquivos de configuracao pessoal de ambiente no `.gitignore`

2021-08-11 01:54 UTC, VitorMartin commented on src/main.py
> +from starlette.requests import Request
O FastAPI já não tem um Request próprio?

2021-08-12 07:56 UTC, VitorMartin requested changes
### 1
Na pasta de `repositórios`, cria só uma pasta pra cada tipo de auth e deleta a pasta `criacao`. Além disso, copiar o mesmo nome da interface nos repos, de acordo com a nossa padronização:

```
repositorios
|
|__ jwt
    |__ authJWT.py
|
|__ oauth
    |__ authOAuth.py
|
|__ otp
    |__ authOTP.py

```

### 2
Testes devem estar contidos numa classe e com `snake_case`, de acordo com nossa padronização. O nome da classe é o mesmo do arquivo e deve se referir ao tipo de teste que será feito. Seguir exemplo dos [tests MSS Ger Usr](https://github.com/Maua-Dev/mss_gerenciamento_usuarios/tree/main/tests).

2021-08-12 07:56 UTC, VitorMartin commented on src/interfaces/i_geracao.py
> +    def chaveInvalido(self, chave: Chave):
chaveInvalid\*a*

2021-08-12 07:56 UTC, VitorMartin commented on src/controladores/c_gerar_token.py
> +class CHTTPGerarToken():
Arquivo: c_gerar_token_fastapi

Classe: CGerarTokenFastAPI

2021-08-12 07:56 UTC, VitorMartin commented on src/interfaces/i_geracao.py
> +class IGeracao(ABC):
Sugestão de nome: `IAuth`

`Auth`, pq essa interface se trata dos serviços de autenticação (criar token, validar acesso etc) do nosso sistema.

Se mudar o nome, não esqueça de atualizar o nome do arquivo também (`i_auth.py`)

2021-08-12 07:56 UTC, VitorMartin commented on src/usecases/uc_chave_invalido.py
> +class UCChaveInvalido():
Arquivo: uc_chave_invalid\*a*.py

Classe: UCChaveInvalid\*a*

2021-08-12 07:59 UTC, VitorMartin requested changes

2021-08-12 07:59 UTC, VitorMartin commented on src/models/token.py
> +    def chaveNaoVazio(cls, v):
chaveNaoVazi\*a*

2021-08-13 03:00 UTC, VitorMartin approved these changes
LGTM

2021-08-13 15:36 UTC, merged